apiVersion : apps/v1
kind: Deployment
metadata:
  name: kubeserve
spec:
  replicas:
  selector:
    matchLabels:
      app: kubeserve
  template:
    matadata:
      name: kubeserve
      labels:
        app: kubeserve
    spec:
      containers:
      - env:
        - name: app
          value: "1" 
        image: linuxacademycontent/kubeserve:v1            